version: '3.8'
services:
  mafia:
    container_name: mafia_server
    image: mafia_server:1.0
    restart: unless-stopped
    environment:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
    ports:
      - 50051:50051
